### ISSUE TITLE
Регистрация нового пользователя

### ISSUE THREAD

**Issue by sergeos** [simlex-titul2005/bazatoday#1]
С главной страницы, при переходе на страницу регистрации нового пользователя нужно отображать окно со следующими полями:
[http://prntscr.com/bqr56s](url)
- [ ] Текст **BazaToday**.
- [ ] Текст **Регистрация нового пользователя**.
- [ ] Поле **Название компании или имя**. Обязательное. До 100 стандартных символов (кирилица + латиница)
- [ ] Поле **Логин** (емеил). Обязательное. Стандартная проверка емеила.
- [ ] Поле **Пароль**. Обязательное. Мин. длина 7 символов. Наличие спецсимволов необязательно.
- [ ] Поле **Повтор пароля**. Обязательное. Дублирует предыдущий пункт.
- [ ] Форма **Капча**. Обязательное. Фильтр от спамеров.
- [ ] Кнопка **Зарегистрироваться**.
- [ ] Текст **Уже зарегистрированы?**.
- [ ] Кнопка **Авторизоваться**.
- [ ] Текст **BazaToday @ 2016**.

**Comment by simlex-titul2005** [comment]
Сделал
