### ISSUE TITLE
Продление сессии под авторизацией

### ISSUE THREAD

**Issue by sergeos** [simlex-titul2005/bazatoday#2]
Желательно установить длительный интервал пребывания авторизованного пользователя в системе. Неделю или две.

**Comment by simlex-titul2005** [comment]
Это нежелательно с точки зрения безопасности...

**Comment by sergeos** [comment]
Безопасность в данном случае не волнует. 
Надо поставить две недели. И кнопку выхода из системы, если надо потереть кукис вдруг принудительно.

**Comment by simlex-titul2005** [comment]
Сделал
